fix: fix potential KeyError in `should_log` if server=on with threads
When running `logset sync` with the server set to "on", the existence of threads causes a crash:

```
Exception in command 'logset sync'
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/activitylog/activitylog.py", line 858, in sync_guild
    await sync_channel(thread)
  File "/data/cogs/CogManager/cogs/activitylog/activitylog.py", line 832, in sync_channel
    if not (self.should_log(channel) or self.should_log(channel.guild)):
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/activitylog/activitylog.py", line 283, in should_log
    self.cache[location.id].get("enabled", default),
    ~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 1250877024034357310

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "/data/venv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 825, in invoke
    await super().invoke(ctx)
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1650, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 1250877024034357310
```

This commit changes the logic of the `should_log` method to ensure the global server setting is respected regardless of the presence of the location in the cache.